site_name: VLSCI User Documentation
theme: flatly 
pages:
- [index.md, "Home"]
- [help.md, "Help"]
- [faq.md, "FAQ"]
- [fundamentals/overview.md, "Fundamentals", "Overview"]
- [fundamentals/using_unix/what_is_unix.md, "Fundamentals", "What is Unix?"]
- [fundamentals/using_unix/login.md, "Fundamentals", "Login and logout"]
- [fundamentals/using_unix/shell.md, "Fundamentals", "The shell"]
- [fundamentals/using_unix/help.md, "Fundamentals", "Getting help"]
- [fundamentals/using_unix/file_system.md, "Fundamentals", "The file system"]
- [fundamentals/using_unix/working_with_files.md, "Fundamentals", "Working with files"]
- [fundamentals/using_unix/processes.md, "Fundamentals", "Processes"]
- [fundamentals/using_unix/shell_scripts.md, "Fundamentals", "Shell scripts"]
- [fundamentals/using_unix/command_summary.md, "Fundamentals", "Command summary"]
- [running_jobs/overview.md, "Running Jobs", "Overview"]
- [running_jobs/slurm_x86.md, "Running Jobs", "Running Jobs on the x86 clusters"]
- [running_jobs/slurm_bluegene.md, "Running Jobs", "Running Jobs on the BlueGene/Q"]
- [software/overview.md, "Software", "Overview"]
- [software/installed_applications.md, "Software", "Installed applications"]
- [resources/overview.md, "Resources", "Overview"]
- [resources/service_units.md, "Resources", "Service units"]
- [resources/storage.md, "Resources", "Managing storage"]
- [resources/memory.md, "Resources", "Memory (RAM) usage"]
